export { default as Header } from './common/Header'
export { default as Footer } from './common/Footer'
export { default as SWRSample } from './SWRSample'
export { default as Knocknock } from './knocknock'
export { default as CardDetection } from './computerVisions/CardDetection'
export { default as ObjectDetection } from './computerVisions/ObjectDetection'
export { default as FaceDetection } from './computerVisions/FaceDetection'
